# Generated by Django 5.0.6 on 2024-08-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('can_delete_newsletter', 'Can delete newsletter'), ('can_view_newsletter', 'Can view newsletter'), ('can_delete_user', 'Can delete user'), ('can_view_user', 'Can view user')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
